function get_menu_data(){
	var ver = 1.1;
	var data = [ {
		"accessPath" : "",
		"checked" : false,
		"delFlag" : 0,
		"parentID" : 1,
		"resourceCode" : "",
		"resourceDesc" : "",
		"resourceGrade" : 2,
		"resourceID" : 10,
		"resourceName" : "激活数据",
		"resourceOrder" : 0,
		"resourceType" : ""
	}, {
		"accessPath" : "views/basic/active_report.html?ver="+ver,
		"checked" : false,
		"delFlag" : 0,
		"parentID" : 10,
		"resourceCode" : "",
		"resourceDesc" : "",
		"resourceGrade" : 3,
		"resourceID" : 11,
		"resourceName" : "活跃数据",
		"resourceOrder" : 0,
		"resourceType" : ""
	}, {
		"accessPath" : "views/basic/active_detail_list.html?ver="+ver,
		"checked" : false,
		"delFlag" : 0,
		"parentID" : 10,
		"resourceCode" : "",
		"resourceDesc" : "",
		"resourceGrade" : 3,
		"resourceID" : 12,
		"resourceName" : "活跃详情",
		"resourceOrder" : 0,
		"resourceType" : ""
	}, {
		"accessPath" : "views/basic/device_list.html?ver="+ver,
		"checked" : false,
		"delFlag" : 0,
		"parentID" : 10,
		"resourceCode" : "",
		"resourceDesc" : "",
		"resourceGrade" : 3,
		"resourceID" : 13,
		"resourceName" : "激活数据",
		"resourceOrder" : 0,
		"resourceType" : ""
	}, {
		"accessPath" : "views/basic/old_device_list.html?ver="+ver,
		"checked" : false,
		"delFlag" : 0,
		"parentID" : 10,
		"resourceCode" : "",
		"resourceDesc" : "",
		"resourceGrade" : 3,
		"resourceID" : 14,
		"resourceName" : "旧版激活数据",
		"resourceOrder" : 0,
		"resourceType" : ""
	}, {
		"accessPath" : "",
		"checked" : false,
		"delFlag" : 0,
		"parentID" : 1,
		"resourceCode" : "",
		"resourceDesc" : "",
		"resourceGrade" : 2,
		"resourceID" : 20,
		"resourceName" : "广告管理",
		"resourceOrder" : 0,
		"resourceType" : ""
	}, {
		"accessPath" : "views/advert/advert_list.html?ver="+ver,
		"checked" : false,
		"delFlag" : 0,
		"parentID" : 20,
		"resourceCode" : "",
		"resourceDesc" : "",
		"resourceGrade" : 3,
		"resourceID" : 21,
		"resourceName" : "广告列表",
		"resourceOrder" : 0,
		"resourceType" : ""
	}, {
		"accessPath" : "views/advert/new_advert_apk.html?ver="+ver,
		"checked" : false,
		"delFlag" : 0,
		"parentID" : 20,
		"resourceCode" : "",
		"resourceDesc" : "",
		"resourceGrade" : 3,
		"resourceID" : 22,
		"resourceName" : "应用推广",
		"resourceOrder" : 0,
		"resourceType" : ""
	}, {
		"accessPath" : "views/advert/new_advert_url.html?ver="+ver,
		"checked" : false,
		"delFlag" : 0,
		"parentID" : 20,
		"resourceCode" : "",
		"resourceDesc" : "",
		"resourceGrade" : 3,
		"resourceID" : 23,
		"resourceName" : "外部链接",
		"resourceOrder" : 0,
		"resourceType" : ""
	} ,{
		"accessPath" : "views/advert/new_advert_push.html?ver="+ver,
		"checked" : false,
		"delFlag" : 0,
		"parentID" : 20,
		"resourceCode" : "",
		"resourceDesc" : "",
		"resourceGrade" : 3,
		"resourceID" : 24,
		"resourceName" : "推送广告",
		"resourceOrder" : 0,
		"resourceType" : ""
	}, {
		"accessPath" : "",
		"checked" : false,
		"delFlag" : 0,
		"parentID" : 1,
		"resourceCode" : "",
		"resourceDesc" : "",
		"resourceGrade" : 2,
		"resourceID" : 30,
		"resourceName" : "规则管理",
		"resourceOrder" : 0,
		"resourceType" : ""
	}, {
		"accessPath" : "views/rule/rule_list.html?ver="+ver,
		"checked" : false,
		"delFlag" : 0,
		"parentID" : 30,
		"resourceCode" : "",
		"resourceDesc" : "",
		"resourceGrade" : 3,
		"resourceID" : 31,
		"resourceName" : "规则列表",
		"resourceOrder" : 0,
		"resourceType" : ""
	}, {
		"accessPath" : "views/rule/new_rule.html?ver="+ver,
		"checked" : false,
		"delFlag" : 0,
		"parentID" : 30,
		"resourceCode" : "",
		"resourceDesc" : "",
		"resourceGrade" : 3,
		"resourceID" : 32,
		"resourceName" : "新增规则",
		"resourceOrder" : 0,
		"resourceType" : ""
	}, {
		"accessPath" : "",
		"checked" : false,
		"delFlag" : 0,
		"parentID" : 1,
		"resourceCode" : "",
		"resourceDesc" : "",
		"resourceGrade" : 2,
		"resourceID" : 40,
		"resourceName" : "渠道管理",
		"resourceOrder" : 0,
		"resourceType" : ""
	}, {
		"accessPath" : "views/channel/channel_list.html?ver="+ver,
		"checked" : false,
		"delFlag" : 0,
		"parentID" : 40,
		"resourceCode" : "",
		"resourceDesc" : "",
		"resourceGrade" : 3,
		"resourceID" : 41,
		"resourceName" : "渠道列表",
		"resourceOrder" : 0,
		"resourceType" : ""
	}, {
		"accessPath" : "views/channel/new_channel.html?ver="+ver,
		"checked" : false,
		"delFlag" : 0,
		"parentID" : 40,
		"resourceCode" : "",
		"resourceDesc" : "",
		"resourceGrade" : 3,
		"resourceID" : 42,
		"resourceName" : "新增渠道",
		"resourceOrder" : 0,
		"resourceType" : ""
	}, {
		"accessPath" : "",
		"checked" : false,
		"delFlag" : 0,
		"parentID" : 1,
		"resourceCode" : "",
		"resourceDesc" : "",
		"resourceGrade" : 2,
		"resourceID" : 50,
		"resourceName" : "组合管理",
		"resourceOrder" : 0,
		"resourceType" : ""
	}, {
		"accessPath" : "views/publish/publish_list.html?ver="+ver,
		"checked" : false,
		"delFlag" : 0,
		"parentID" : 50,
		"resourceCode" : "",
		"resourceDesc" : "",
		"resourceGrade" : 3,
		"resourceID" : 51,
		"resourceName" : "组合列表",
		"resourceOrder" : 0,
		"resourceType" : ""
	}, {
		"accessPath" : "views/publish/new_publish.html?ver="+ver,
		"checked" : false,
		"delFlag" : 0,
		"parentID" : 50,
		"resourceCode" : "",
		"resourceDesc" : "",
		"resourceGrade" : 3,
		"resourceID" : 52,
		"resourceName" : "新增组合",
		"resourceOrder" : 0,
		"resourceType" : ""
	}, {
		"accessPath" : "views/publish/publish_list.html?ver="+ver,
		"checked" : false,
		"delFlag" : 0,
		"parentID" : 1,
		"resourceCode" : "",
		"resourceDesc" : "",
		"resourceGrade" : 3,
		"resourceID" : 60,
		"resourceName" : "元数据",
		"resourceOrder" : 0,
		"resourceType" : ""
	}, {
		"accessPath" : "views/meta/city.html?ver="+ver,
		"checked" : false,
		"delFlag" : 0,
		"parentID" : 60,
		"resourceCode" : "",
		"resourceDesc" : "",
		"resourceGrade" : 3,
		"resourceID" : 61,
		"resourceName" : "城市",
		"resourceOrder" : 0,
		"resourceType" : ""
	}, {
		"accessPath" : "views/meta/brand.html?ver="+ver,
		"checked" : false,
		"delFlag" : 0,
		"parentID" : 60,
		"resourceCode" : "",
		"resourceDesc" : "",
		"resourceGrade" : 3,
		"resourceID" : 62,
		"resourceName" : "品牌",
		"resourceOrder" : 0,
		"resourceType" : ""
	}, {
		"accessPath" : "views/meta/isp.html?ver="+ver,
		"checked" : false,
		"delFlag" : 0,
		"parentID" : 60,
		"resourceCode" : "",
		"resourceDesc" : "",
		"resourceGrade" : 3,
		"resourceID" : 63,
		"resourceName" : "运营商",
		"resourceOrder" : 0,
		"resourceType" : ""
	}, {
		"accessPath" : "views/meta/network.html?ver="+ver,
		"checked" : false,
		"delFlag" : 0,
		"parentID" : 60,
		"resourceCode" : "",
		"resourceDesc" : "",
		"resourceGrade" : 3,
		"resourceID" : 64,
		"resourceName" : "网络",
		"resourceOrder" : 0,
		"resourceType" : ""
	}, {
		"accessPath" : "views/meta/os.html?ver="+ver,
		"checked" : false,
		"delFlag" : 0,
		"parentID" : 60,
		"resourceCode" : "",
		"resourceDesc" : "",
		"resourceGrade" : 3,
		"resourceID" : 65,
		"resourceName" : "系统",
		"resourceOrder" : 0,
		"resourceType" : ""
	}, {
		"accessPath" : "",
		"checked" : false,
		"delFlag" : 0,
		"parentID" : 1,
		"resourceCode" : "",
		"resourceDesc" : "",
		"resourceGrade" : 2,
		"resourceID" : 70,
		"resourceName" : "系统管理",
		"resourceOrder" : 0,
		"resourceType" : ""
	}, {
		"accessPath" : "views/plugin/plugin_list.html?ver="+ver,
		"checked" : false,
		"delFlag" : 0,
		"parentID" : 70,
		"resourceCode" : "",
		"resourceDesc" : "",
		"resourceGrade" : 3,
		"resourceID" : 71,
		"resourceName" : "插件列表",
		"resourceOrder" : 0,
		"resourceType" : ""
	}, {
		"accessPath" : "views/plugin/new_plugin.html?ver="+ver,
		"checked" : false,
		"delFlag" : 0,
		"parentID" : 70,
		"resourceCode" : "",
		"resourceDesc" : "",
		"resourceGrade" : 3,
		"resourceID" : 72,
		"resourceName" : "新增插件",
		"resourceOrder" : 0,
		"resourceType" : ""
	} ];
	
	return data;
}
